### ISSUE TITLE
What is the exact UE version of this project?

### ISSUE THREAD

**Issue by ibreathebsb** [AyoubKhammassi/CustomMeshComponent#5]

**Comment by Smartuil** [comment]
4.26.2，work

**Comment by ibreathebsb** [comment]
if you are looking for a version that works for UE5 check this out 
https://github.com/ibreathebsb/CustomVertexFactory

**Comment by Smartuil** [comment]
> if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory

Thank you so much

**Comment by Smartuil** [comment]
> if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory

太感谢了老哥

**Comment by ibreathebsb** [comment]
> > if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory
> 
> 太感谢了老哥

It took me a month,star if you like it 😀
also see https://github.com/ibreathebsb/CustomGlobalShader for unreal GlobalShader

**Comment by Smartuil** [comment]
> > > if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory
> > 
> > 
> > 太感谢了老哥
> 
> It took me a month,star if you like it 😀 also see https://github.com/ibreathebsb/CustomGlobalShader for unreal GlobalShader

老哥，作者的这个项目你在UE5验证出正确的效果了吗？我现在跑起来没有形变效果

**Comment by ibreathebsb** [comment]
> > > > if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory
> > > 
> > > 
> > > 太感谢了老哥
> > 
> > 
> > It took me a month,star if you like it 😀 also see https://github.com/ibreathebsb/CustomGlobalShader for unreal GlobalShader
> 
> 老哥，作者的这个项目你在UE5验证出正确的效果了吗？我现在跑起来没有形变效果

不是变形效果,自定义的顶点数据,你可以在ShaderTest.ush修改顶点着色器逻辑,现在是画了100个三角形

https://medium.com/realities-io/creating-a-custom-mesh-component-in-ue4-part-0-intro-2c762c5f0cd6

**Comment by Smartuil** [comment]
> > > > > if you are looking for a version that works for UE5 check this out https://github.com/ibreathebsb/CustomVertexFactory
> > > > 
> > > > 
> > > > 太感谢了老哥
> > > 
> > > 
> > > It took me a month,star if you like it 😀 also see https://github.com/ibreathebsb/CustomGlobalShader for unreal GlobalShader
> > 
> > 
> > 老哥，作者的这个项目你在UE5验证出正确的效果了吗？我现在跑起来没有形变效果
> 
> 不是变形效果,自定义的顶点数据,你可以在ShaderTest.ush修改顶点着色器逻辑,现在是画了100个三角形
> 
> https://medium.com/realities-io/creating-a-custom-mesh-component-in-ue4-part-0-intro-2c762c5f0cd6

好的好的，我学习一下，感谢
